version: '3.8'

services:
    nginx:
        image: nginx:alpine
        container_name: laravel_nginx_product
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www/html:delegated
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app

    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: laravel-app-product
        container_name: laravel_app_product
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html:delegated
        depends_on:
            - mysql
            - redis
            - rabbitmq
        environment:
            - DB_HOST=mysql
            - DB_PORT=3306
            - DB_DATABASE=laravel-product
            - DB_USERNAME=root
            - DB_PASSWORD=password
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - QUEUE_CONNECTION=rabbitmq
            - RABBITMQ_HOST=rabbitmq
            - RABBITMQ_PORT=5672
            - RABBITMQ_USER=guest
            - RABBITMQ_PASSWORD=guest
        user: "${UID:-1000}:${GID:-1000}"

    mysql:
        image: mysql:8.0
        container_name: laravel_mysql_product
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: laravel-product
        ports:
            - "3307:3306"
        volumes:
            - mysql_data_product:/var/lib/mysql

    redis:
        image: redis:alpine
        container_name: laravel_redis_product
        restart: unless-stopped
        ports:
            - "6379:6379"

    rabbitmq:
        build:
            context: ./docker/rabbitmq
            dockerfile: Dockerfile
        container_name: laravel_rabbitmq_product
        restart: unless-stopped
        ports:
            - "5672:5672"
            - "15672:15672" # Management UI
        environment:
            RABBITMQ_DEFAULT_USER: guest
            RABBITMQ_DEFAULT_PASS: guest
        volumes:
            - rabbitmq-data:/var/lib/rabbitmq

    laravel-worker:
        build:
            context: .
            dockerfile: Dockerfile
        command: php artisan queue:work rabbitmq --sleep=1 --tries=3 --timeout=90 --queue=rental-management
        depends_on:
            - rabbitmq
        volumes:
            - .:/var/www/html
        environment:
            - DB_HOST=mysql
            - DB_PORT=3306
            - DB_DATABASE=laravel-product
            - DB_USERNAME=root
            - DB_PASSWORD=password
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - QUEUE_CONNECTION=rabbitmq
            - RABBITMQ_HOST=rabbitmq
            - RABBITMQ_PORT=5672
            - RABBITMQ_USER=guest
            - RABBITMQ_PASSWORD=guest

volumes:
    mysql_data_product:
    rabbitmq-data:
